defmodule Me.Repo.Migrations.CreateSales do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount_cents, :bigint, null: false
      add :method, :text, null: false
      add :note, :text

      add :recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :voided_at, :utc_datetime_usec
      add :order_id, :uuid, null: false
      add :recorded_by_user_id, :uuid, null: false
    end

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payments) do
      modify :order_id,
             references(:orders,
               column: :id,
               name: "payments_order_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :recorded_by_user_id,
             references(:users,
               column: :id,
               name: "payments_recorded_by_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:payments, [:order_id])

    alter table(:orders) do
      add :order_number, :bigserial, null: false
      add :status, :text, null: false, default: "draft"
      add :subtotal_cents, :bigint, null: false, default: 0
      add :discount_cents, :bigint, null: false, default: 0
      add :placed_at, :utc_datetime_usec
      add :fulfilled_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec
      add :cancel_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:customers,
            column: :id,
            name: "orders_customer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :placed_by_user_id,
          references(:users,
            column: :id,
            name: "orders_placed_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:orders, [:order_number], name: "orders_unique_order_number_index")
    create index(:orders, [:customer_id, :placed_at])

    create table(:order_line_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false
      add :unit_price_cents, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_line_items_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_variant_id,
          references(:product_variants,
            column: :id,
            name: "order_line_items_product_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:order_line_items, [:order_id, :product_variant_id],
             name: "order_line_items_unique_order_variant_index"
           )

    create index(:order_line_items, [:order_id])
  end

  def down do
    drop constraint(:order_line_items, "order_line_items_order_id_fkey")

    drop constraint(:order_line_items, "order_line_items_product_variant_id_fkey")

    drop_if_exists unique_index(:order_line_items, [:order_id, :product_variant_id],
                     name: "order_line_items_unique_order_variant_index"
                   )

    drop table(:order_line_items)

    drop constraint(:orders, "orders_customer_id_fkey")

    drop constraint(:orders, "orders_placed_by_user_id_fkey")

    drop_if_exists unique_index(:orders, [:order_number],
                     name: "orders_unique_order_number_index"
                   )

    alter table(:orders) do
      remove :placed_by_user_id
      remove :customer_id
      remove :updated_at
      remove :inserted_at
      remove :cancel_reason
      remove :cancelled_at
      remove :fulfilled_at
      remove :placed_at
      remove :discount_cents
      remove :subtotal_cents
      remove :status
      remove :order_number
    end

    drop constraint(:payments, "payments_order_id_fkey")

    drop constraint(:payments, "payments_recorded_by_user_id_fkey")

    alter table(:payments) do
      modify :recorded_by_user_id, :uuid
      modify :order_id, :uuid
    end

    drop table(:orders)

    drop table(:payments)
  end
end
