defmodule Me.Repo.Migrations.CreateAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :name, :text
      add :role, :text, null: false, default: "staff"
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("UPDATE users SET name = split_part(email::text, '@', 1) WHERE name IS NULL")

    alter table(:users) do
      modify :name, :text, null: false
    end

    create table(:customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext
      add :hashed_password, :text
      add :name, :text, null: false
      add :phone, :text
      add :customer_type, :text, null: false, default: "retail"
      add :business_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_user_id,
          references(:users,
            column: :id,
            name: "customers_created_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:customers, [:email], name: "customers_unique_email_index")
  end

  def down do
    drop constraint(:customers, "customers_created_by_user_id_fkey")

    drop_if_exists unique_index(:customers, [:email], name: "customers_unique_email_index")

    drop table(:customers)

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :role
      remove :name
    end
  end
end
