defmodule Me.Repo.Migrations.CreateCatalog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :category, :text
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:product_variants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sku, :text, null: false
      add :size, :text, null: false
      add :color, :text, null: false
      add :price_cents, :bigint, null: false
      add :quantity_on_hand, :bigint, null: false, default: 0
      add :barcode, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:products,
            column: :id,
            name: "product_variants_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:product_variants, [:product_id, :size, :color],
             name: "product_variants_unique_product_size_color_index"
           )

    create unique_index(:product_variants, [:sku], name: "product_variants_unique_sku_index")

    create constraint(:product_variants, :quantity_on_hand_non_negative,
             check: "quantity_on_hand >= 0"
           )
  end

  def down do
    drop constraint(:product_variants, :quantity_on_hand_non_negative)

    drop constraint(:product_variants, "product_variants_product_id_fkey")

    drop_if_exists unique_index(:product_variants, [:sku],
                     name: "product_variants_unique_sku_index"
                   )

    drop_if_exists unique_index(:product_variants, [:product_id, :size, :color],
                     name: "product_variants_unique_product_size_color_index"
                   )

    drop table(:product_variants)

    drop table(:products)
  end
end
