defmodule Me.Repo.Migrations.CreateInventory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stock_movements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :delta, :bigint, null: false
      add :reason, :text, null: false
      add :reference_type, :text
      add :reference_id, :uuid
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_variant_id,
          references(:product_variants,
            column: :id,
            name: "stock_movements_product_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :actor_id,
          references(:users,
            column: :id,
            name: "stock_movements_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:stock_movements, [:product_variant_id])
  end

  def down do
    drop constraint(:stock_movements, "stock_movements_product_variant_id_fkey")

    drop constraint(:stock_movements, "stock_movements_actor_id_fkey")

    drop table(:stock_movements)
  end
end
